apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-services
  namespace: shop-maram
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx      # يطابق الـIngress Controller
  rules:
    - host: 48.193.24.54.nip.io  # الـStatic IP الجديد
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
