apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: shop-maram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shopmaramacr.azurecr.io/backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_SERVER
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
            - name: DB_ENCRYPT
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_ENCRYPT
            - name: DB_TRUST_SERVER_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_TRUST_SERVER_CERTIFICATE
            - name: DB_CONNECTION_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_CONNECTION_TIMEOUT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CORS_ORIGIN
            - name: RATE_LIMIT_WINDOW_MS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RATE_LIMIT_WINDOW_MS
            - name: RATE_LIMIT_MAX_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RATE_LIMIT_MAX_REQUESTS
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
          command: ["node", "dist/server.js"]
      imagePullSecrets:
        - name: acr-secret